// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.2
// source: api/proto/messenger/v1/messenger.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatFilter int32

const (
	ChatFilter_CHAT_FILTER_ALL ChatFilter = 0
	ChatFilter_CHAT_FILTER_MY  ChatFilter = 1
)

// Enum value maps for ChatFilter.
var (
	ChatFilter_name = map[int32]string{
		0: "CHAT_FILTER_ALL",
		1: "CHAT_FILTER_MY",
	}
	ChatFilter_value = map[string]int32{
		"CHAT_FILTER_ALL": 0,
		"CHAT_FILTER_MY":  1,
	}
)

func (x ChatFilter) Enum() *ChatFilter {
	p := new(ChatFilter)
	*p = x
	return p
}

func (x ChatFilter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatFilter) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_messenger_v1_messenger_proto_enumTypes[0].Descriptor()
}

func (ChatFilter) Type() protoreflect.EnumType {
	return &file_api_proto_messenger_v1_messenger_proto_enumTypes[0]
}

func (x ChatFilter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatFilter.Descriptor instead.
func (ChatFilter) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_messenger_v1_messenger_proto_rawDescGZIP(), []int{0}
}

type SortOrder int32

const (
	SortOrder_SORT_ORDER_UNSPECIFIED SortOrder = 0
	SortOrder_SORT_ORDER_ASC         SortOrder = 1
	SortOrder_SORT_ORDER_DESC        SortOrder = 2
)

// Enum value maps for SortOrder.
var (
	SortOrder_name = map[int32]string{
		0: "SORT_ORDER_UNSPECIFIED",
		1: "SORT_ORDER_ASC",
		2: "SORT_ORDER_DESC",
	}
	SortOrder_value = map[string]int32{
		"SORT_ORDER_UNSPECIFIED": 0,
		"SORT_ORDER_ASC":         1,
		"SORT_ORDER_DESC":        2,
	}
)

func (x SortOrder) Enum() *SortOrder {
	p := new(SortOrder)
	*p = x
	return p
}

func (x SortOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_messenger_v1_messenger_proto_enumTypes[1].Descriptor()
}

func (SortOrder) Type() protoreflect.EnumType {
	return &file_api_proto_messenger_v1_messenger_proto_enumTypes[1]
}

func (x SortOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortOrder.Descriptor instead.
func (SortOrder) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_messenger_v1_messenger_proto_rawDescGZIP(), []int{1}
}

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_messenger_v1_messenger_proto_rawDescGZIP(), []int{0}
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_messenger_v1_messenger_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CreateChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsReadOnly    *bool                  `protobuf:"varint,3,opt,name=is_read_only,json=isReadOnly,proto3,oneof" json:"is_read_only,omitempty"`
	ChatTtl       *durationpb.Duration   `protobuf:"bytes,4,opt,name=chat_ttl,json=chatTtl,proto3,oneof" json:"chat_ttl,omitempty"`
	MessageTtl    *durationpb.Duration   `protobuf:"bytes,5,opt,name=message_ttl,json=messageTtl,proto3,oneof" json:"message_ttl,omitempty"`
	MaxMessages   *int32                 `protobuf:"varint,6,opt,name=max_messages,json=maxMessages,proto3,oneof" json:"max_messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChatRequest) Reset() {
	*x = CreateChatRequest{}
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatRequest) ProtoMessage() {}

func (x *CreateChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatRequest.ProtoReflect.Descriptor instead.
func (*CreateChatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_messenger_v1_messenger_proto_rawDescGZIP(), []int{2}
}

func (x *CreateChatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateChatRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateChatRequest) GetIsReadOnly() bool {
	if x != nil && x.IsReadOnly != nil {
		return *x.IsReadOnly
	}
	return false
}

func (x *CreateChatRequest) GetChatTtl() *durationpb.Duration {
	if x != nil {
		return x.ChatTtl
	}
	return nil
}

func (x *CreateChatRequest) GetMessageTtl() *durationpb.Duration {
	if x != nil {
		return x.MessageTtl
	}
	return nil
}

func (x *CreateChatRequest) GetMaxMessages() int32 {
	if x != nil && x.MaxMessages != nil {
		return *x.MaxMessages
	}
	return 0
}

type CreateChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChatResponse) Reset() {
	*x = CreateChatResponse{}
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatResponse) ProtoMessage() {}

func (x *CreateChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatResponse.ProtoReflect.Descriptor instead.
func (*CreateChatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_messenger_v1_messenger_proto_rawDescGZIP(), []int{3}
}

func (x *CreateChatResponse) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type ListChatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Filter        ChatFilter             `protobuf:"varint,2,opt,name=filter,proto3,enum=messenger.v1.ChatFilter" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatsRequest) Reset() {
	*x = ListChatsRequest{}
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatsRequest) ProtoMessage() {}

func (x *ListChatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatsRequest.ProtoReflect.Descriptor instead.
func (*ListChatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_messenger_v1_messenger_proto_rawDescGZIP(), []int{4}
}

func (x *ListChatsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ListChatsRequest) GetFilter() ChatFilter {
	if x != nil {
		return x.Filter
	}
	return ChatFilter_CHAT_FILTER_ALL
}

type ListChatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chats         []*ChatInfo            `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatsResponse) Reset() {
	*x = ListChatsResponse{}
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatsResponse) ProtoMessage() {}

func (x *ListChatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatsResponse.ProtoReflect.Descriptor instead.
func (*ListChatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_messenger_v1_messenger_proto_rawDescGZIP(), []int{5}
}

func (x *ListChatsResponse) GetChats() []*ChatInfo {
	if x != nil {
		return x.Chats
	}
	return nil
}

type ChatInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsReadOnly    bool                   `protobuf:"varint,3,opt,name=is_read_only,json=isReadOnly,proto3" json:"is_read_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatInfo) Reset() {
	*x = ChatInfo{}
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatInfo) ProtoMessage() {}

func (x *ChatInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatInfo.ProtoReflect.Descriptor instead.
func (*ChatInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_messenger_v1_messenger_proto_rawDescGZIP(), []int{6}
}

func (x *ChatInfo) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ChatInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChatInfo) GetIsReadOnly() bool {
	if x != nil {
		return x.IsReadOnly
	}
	return false
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Message       *ChatMessage           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_messenger_v1_messenger_proto_rawDescGZIP(), []int{7}
}

func (x *SendMessageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendMessageRequest) GetMessage() *ChatMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_messenger_v1_messenger_proto_rawDescGZIP(), []int{8}
}

type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ChatId        string                 `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	SortOrder     SortOrder              `protobuf:"varint,5,opt,name=sort_order,json=sortOrder,proto3,enum=messenger.v1.SortOrder" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_messenger_v1_messenger_proto_rawDescGZIP(), []int{9}
}

func (x *GetHistoryRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetHistoryRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *GetHistoryRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetHistoryRequest) GetSortOrder() SortOrder {
	if x != nil {
		return x.SortOrder
	}
	return SortOrder_SORT_ORDER_UNSPECIFIED
}

type GetHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResponse) Reset() {
	*x = GetHistoryResponse{}
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponse) ProtoMessage() {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_messenger_v1_messenger_proto_rawDescGZIP(), []int{10}
}

func (x *GetHistoryResponse) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetHistoryResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SenderId      string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_messenger_v1_messenger_proto_rawDescGZIP(), []int{11}
}

func (x *ChatMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ChatMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ChatMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChatMessage) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

var File_api_proto_messenger_v1_messenger_proto protoreflect.FileDescriptor

const file_api_proto_messenger_v1_messenger_proto_rawDesc = "" +
	"\n" +
	"&api/proto/messenger/v1/messenger.proto\x12\fmessenger.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\x16\n" +
	"\x14CreateSessionRequest\"6\n" +
	"\x15CreateSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xd0\x02\n" +
	"\x11CreateChatRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\fis_read_only\x18\x03 \x01(\bH\x00R\n" +
	"isReadOnly\x88\x01\x01\x129\n" +
	"\bchat_ttl\x18\x04 \x01(\v2\x19.google.protobuf.DurationH\x01R\achatTtl\x88\x01\x01\x12?\n" +
	"\vmessage_ttl\x18\x05 \x01(\v2\x19.google.protobuf.DurationH\x02R\n" +
	"messageTtl\x88\x01\x01\x12&\n" +
	"\fmax_messages\x18\x06 \x01(\x05H\x03R\vmaxMessages\x88\x01\x01B\x0f\n" +
	"\r_is_read_onlyB\v\n" +
	"\t_chat_ttlB\x0e\n" +
	"\f_message_ttlB\x0f\n" +
	"\r_max_messages\"-\n" +
	"\x12CreateChatResponse\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\"c\n" +
	"\x10ListChatsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x120\n" +
	"\x06filter\x18\x02 \x01(\x0e2\x18.messenger.v1.ChatFilterR\x06filter\"A\n" +
	"\x11ListChatsResponse\x12,\n" +
	"\x05chats\x18\x01 \x03(\v2\x16.messenger.v1.ChatInfoR\x05chats\"Y\n" +
	"\bChatInfo\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\fis_read_only\x18\x03 \x01(\bR\n" +
	"isReadOnly\"h\n" +
	"\x12SendMessageRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x123\n" +
	"\amessage\x18\x02 \x01(\v2\x19.messenger.v1.ChatMessageR\amessage\"\x15\n" +
	"\x13SendMessageResponse\"\xb1\x01\n" +
	"\x11GetHistoryRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x126\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\x0e2\x17.messenger.v1.SortOrderR\tsortOrder\"l\n" +
	"\x12GetHistoryResponse\x125\n" +
	"\bmessages\x18\x01 \x03(\v2\x19.messenger.v1.ChatMessageR\bmessages\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\x92\x01\n" +
	"\vChatMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x123\n" +
	"\asent_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt*5\n" +
	"\n" +
	"ChatFilter\x12\x13\n" +
	"\x0fCHAT_FILTER_ALL\x10\x00\x12\x12\n" +
	"\x0eCHAT_FILTER_MY\x10\x01*P\n" +
	"\tSortOrder\x12\x1a\n" +
	"\x16SORT_ORDER_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSORT_ORDER_ASC\x10\x01\x12\x13\n" +
	"\x0fSORT_ORDER_DESC\x10\x022\xa9\x03\n" +
	"\tMessenger\x12X\n" +
	"\rCreateSession\x12\".messenger.v1.CreateSessionRequest\x1a#.messenger.v1.CreateSessionResponse\x12O\n" +
	"\n" +
	"CreateChat\x12\x1f.messenger.v1.CreateChatRequest\x1a .messenger.v1.CreateChatResponse\x12L\n" +
	"\tListChats\x12\x1e.messenger.v1.ListChatsRequest\x1a\x1f.messenger.v1.ListChatsResponse\x12R\n" +
	"\vSendMessage\x12 .messenger.v1.SendMessageRequest\x1a!.messenger.v1.SendMessageResponse\x12O\n" +
	"\n" +
	"GetHistory\x12\x1f.messenger.v1.GetHistoryRequest\x1a .messenger.v1.GetHistoryResponseB.Z,github.com/aniats/messenger/pkg/messenger/v1b\x06proto3"

var (
	file_api_proto_messenger_v1_messenger_proto_rawDescOnce sync.Once
	file_api_proto_messenger_v1_messenger_proto_rawDescData []byte
)

func file_api_proto_messenger_v1_messenger_proto_rawDescGZIP() []byte {
	file_api_proto_messenger_v1_messenger_proto_rawDescOnce.Do(func() {
		file_api_proto_messenger_v1_messenger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_messenger_v1_messenger_proto_rawDesc), len(file_api_proto_messenger_v1_messenger_proto_rawDesc)))
	})
	return file_api_proto_messenger_v1_messenger_proto_rawDescData
}

var file_api_proto_messenger_v1_messenger_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_messenger_v1_messenger_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_proto_messenger_v1_messenger_proto_goTypes = []any{
	(ChatFilter)(0),               // 0: messenger.v1.ChatFilter
	(SortOrder)(0),                // 1: messenger.v1.SortOrder
	(*CreateSessionRequest)(nil),  // 2: messenger.v1.CreateSessionRequest
	(*CreateSessionResponse)(nil), // 3: messenger.v1.CreateSessionResponse
	(*CreateChatRequest)(nil),     // 4: messenger.v1.CreateChatRequest
	(*CreateChatResponse)(nil),    // 5: messenger.v1.CreateChatResponse
	(*ListChatsRequest)(nil),      // 6: messenger.v1.ListChatsRequest
	(*ListChatsResponse)(nil),     // 7: messenger.v1.ListChatsResponse
	(*ChatInfo)(nil),              // 8: messenger.v1.ChatInfo
	(*SendMessageRequest)(nil),    // 9: messenger.v1.SendMessageRequest
	(*SendMessageResponse)(nil),   // 10: messenger.v1.SendMessageResponse
	(*GetHistoryRequest)(nil),     // 11: messenger.v1.GetHistoryRequest
	(*GetHistoryResponse)(nil),    // 12: messenger.v1.GetHistoryResponse
	(*ChatMessage)(nil),           // 13: messenger.v1.ChatMessage
	(*durationpb.Duration)(nil),   // 14: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
}
var file_api_proto_messenger_v1_messenger_proto_depIdxs = []int32{
	14, // 0: messenger.v1.CreateChatRequest.chat_ttl:type_name -> google.protobuf.Duration
	14, // 1: messenger.v1.CreateChatRequest.message_ttl:type_name -> google.protobuf.Duration
	0,  // 2: messenger.v1.ListChatsRequest.filter:type_name -> messenger.v1.ChatFilter
	8,  // 3: messenger.v1.ListChatsResponse.chats:type_name -> messenger.v1.ChatInfo
	13, // 4: messenger.v1.SendMessageRequest.message:type_name -> messenger.v1.ChatMessage
	1,  // 5: messenger.v1.GetHistoryRequest.sort_order:type_name -> messenger.v1.SortOrder
	13, // 6: messenger.v1.GetHistoryResponse.messages:type_name -> messenger.v1.ChatMessage
	15, // 7: messenger.v1.ChatMessage.sent_at:type_name -> google.protobuf.Timestamp
	2,  // 8: messenger.v1.Messenger.CreateSession:input_type -> messenger.v1.CreateSessionRequest
	4,  // 9: messenger.v1.Messenger.CreateChat:input_type -> messenger.v1.CreateChatRequest
	6,  // 10: messenger.v1.Messenger.ListChats:input_type -> messenger.v1.ListChatsRequest
	9,  // 11: messenger.v1.Messenger.SendMessage:input_type -> messenger.v1.SendMessageRequest
	11, // 12: messenger.v1.Messenger.GetHistory:input_type -> messenger.v1.GetHistoryRequest
	3,  // 13: messenger.v1.Messenger.CreateSession:output_type -> messenger.v1.CreateSessionResponse
	5,  // 14: messenger.v1.Messenger.CreateChat:output_type -> messenger.v1.CreateChatResponse
	7,  // 15: messenger.v1.Messenger.ListChats:output_type -> messenger.v1.ListChatsResponse
	10, // 16: messenger.v1.Messenger.SendMessage:output_type -> messenger.v1.SendMessageResponse
	12, // 17: messenger.v1.Messenger.GetHistory:output_type -> messenger.v1.GetHistoryResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_proto_messenger_v1_messenger_proto_init() }
func file_api_proto_messenger_v1_messenger_proto_init() {
	if File_api_proto_messenger_v1_messenger_proto != nil {
		return
	}
	file_api_proto_messenger_v1_messenger_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_messenger_v1_messenger_proto_rawDesc), len(file_api_proto_messenger_v1_messenger_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_messenger_v1_messenger_proto_goTypes,
		DependencyIndexes: file_api_proto_messenger_v1_messenger_proto_depIdxs,
		EnumInfos:         file_api_proto_messenger_v1_messenger_proto_enumTypes,
		MessageInfos:      file_api_proto_messenger_v1_messenger_proto_msgTypes,
	}.Build()
	File_api_proto_messenger_v1_messenger_proto = out.File
	file_api_proto_messenger_v1_messenger_proto_goTypes = nil
	file_api_proto_messenger_v1_messenger_proto_depIdxs = nil
}
