// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.2
// source: api/proto/messenger/v1/messenger.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_messenger_v1_messenger_proto_rawDescGZIP(), []int{0}
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_messenger_v1_messenger_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CreateChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsReadOnly    *bool                  `protobuf:"varint,3,opt,name=is_read_only,json=isReadOnly,proto3,oneof" json:"is_read_only,omitempty"`
	ChatTtl       *durationpb.Duration   `protobuf:"bytes,4,opt,name=chat_ttl,json=chatTtl,proto3,oneof" json:"chat_ttl,omitempty"`
	MessageTtl    *durationpb.Duration   `protobuf:"bytes,5,opt,name=message_ttl,json=messageTtl,proto3,oneof" json:"message_ttl,omitempty"`
	MaxMessages   *int32                 `protobuf:"varint,6,opt,name=max_messages,json=maxMessages,proto3,oneof" json:"max_messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChatRequest) Reset() {
	*x = CreateChatRequest{}
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatRequest) ProtoMessage() {}

func (x *CreateChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatRequest.ProtoReflect.Descriptor instead.
func (*CreateChatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_messenger_v1_messenger_proto_rawDescGZIP(), []int{2}
}

func (x *CreateChatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateChatRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateChatRequest) GetIsReadOnly() bool {
	if x != nil && x.IsReadOnly != nil {
		return *x.IsReadOnly
	}
	return false
}

func (x *CreateChatRequest) GetChatTtl() *durationpb.Duration {
	if x != nil {
		return x.ChatTtl
	}
	return nil
}

func (x *CreateChatRequest) GetMessageTtl() *durationpb.Duration {
	if x != nil {
		return x.MessageTtl
	}
	return nil
}

func (x *CreateChatRequest) GetMaxMessages() int32 {
	if x != nil && x.MaxMessages != nil {
		return *x.MaxMessages
	}
	return 0
}

type CreateChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChatResponse) Reset() {
	*x = CreateChatResponse{}
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatResponse) ProtoMessage() {}

func (x *CreateChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatResponse.ProtoReflect.Descriptor instead.
func (*CreateChatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_messenger_v1_messenger_proto_rawDescGZIP(), []int{3}
}

func (x *CreateChatResponse) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ChatId        string                 `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_messenger_v1_messenger_proto_rawDescGZIP(), []int{4}
}

func (x *SendMessageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendMessageRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *SendMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_messenger_v1_messenger_proto_rawDescGZIP(), []int{5}
}

type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ChatId        string                 `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_messenger_v1_messenger_proto_rawDescGZIP(), []int{6}
}

func (x *GetHistoryRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetHistoryRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *GetHistoryRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResponse) Reset() {
	*x = GetHistoryResponse{}
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponse) ProtoMessage() {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_messenger_v1_messenger_proto_rawDescGZIP(), []int{7}
}

func (x *GetHistoryResponse) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetHistoryResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SenderId      string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_messenger_v1_messenger_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_messenger_v1_messenger_proto_rawDescGZIP(), []int{8}
}

func (x *ChatMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ChatMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ChatMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChatMessage) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

var File_api_proto_messenger_v1_messenger_proto protoreflect.FileDescriptor

const file_api_proto_messenger_v1_messenger_proto_rawDesc = "" +
	"\n" +
	"&api/proto/messenger/v1/messenger.proto\x12\fmessenger.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\x16\n" +
	"\x14CreateSessionRequest\"6\n" +
	"\x15CreateSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xd0\x02\n" +
	"\x11CreateChatRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\fis_read_only\x18\x03 \x01(\bH\x00R\n" +
	"isReadOnly\x88\x01\x01\x129\n" +
	"\bchat_ttl\x18\x04 \x01(\v2\x19.google.protobuf.DurationH\x01R\achatTtl\x88\x01\x01\x12?\n" +
	"\vmessage_ttl\x18\x05 \x01(\v2\x19.google.protobuf.DurationH\x02R\n" +
	"messageTtl\x88\x01\x01\x12&\n" +
	"\fmax_messages\x18\x06 \x01(\x05H\x03R\vmaxMessages\x88\x01\x01B\x0f\n" +
	"\r_is_read_onlyB\v\n" +
	"\t_chat_ttlB\x0e\n" +
	"\f_message_ttlB\x0f\n" +
	"\r_max_messages\"-\n" +
	"\x12CreateChatResponse\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\"`\n" +
	"\x12SendMessageRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"\x15\n" +
	"\x13SendMessageResponse\"y\n" +
	"\x11GetHistoryRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"l\n" +
	"\x12GetHistoryResponse\x125\n" +
	"\bmessages\x18\x01 \x03(\v2\x19.messenger.v1.ChatMessageR\bmessages\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\x92\x01\n" +
	"\vChatMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x123\n" +
	"\asent_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt2\xdb\x02\n" +
	"\tMessenger\x12X\n" +
	"\rCreateSession\x12\".messenger.v1.CreateSessionRequest\x1a#.messenger.v1.CreateSessionResponse\x12O\n" +
	"\n" +
	"CreateChat\x12\x1f.messenger.v1.CreateChatRequest\x1a .messenger.v1.CreateChatResponse\x12R\n" +
	"\vSendMessage\x12 .messenger.v1.SendMessageRequest\x1a!.messenger.v1.SendMessageResponse\x12O\n" +
	"\n" +
	"GetHistory\x12\x1f.messenger.v1.GetHistoryRequest\x1a .messenger.v1.GetHistoryResponseB\x1cZ\x1amessenger/pkg/messenger/v1b\x06proto3"

var (
	file_api_proto_messenger_v1_messenger_proto_rawDescOnce sync.Once
	file_api_proto_messenger_v1_messenger_proto_rawDescData []byte
)

func file_api_proto_messenger_v1_messenger_proto_rawDescGZIP() []byte {
	file_api_proto_messenger_v1_messenger_proto_rawDescOnce.Do(func() {
		file_api_proto_messenger_v1_messenger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_messenger_v1_messenger_proto_rawDesc), len(file_api_proto_messenger_v1_messenger_proto_rawDesc)))
	})
	return file_api_proto_messenger_v1_messenger_proto_rawDescData
}

var file_api_proto_messenger_v1_messenger_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_proto_messenger_v1_messenger_proto_goTypes = []any{
	(*CreateSessionRequest)(nil),  // 0: messenger.v1.CreateSessionRequest
	(*CreateSessionResponse)(nil), // 1: messenger.v1.CreateSessionResponse
	(*CreateChatRequest)(nil),     // 2: messenger.v1.CreateChatRequest
	(*CreateChatResponse)(nil),    // 3: messenger.v1.CreateChatResponse
	(*SendMessageRequest)(nil),    // 4: messenger.v1.SendMessageRequest
	(*SendMessageResponse)(nil),   // 5: messenger.v1.SendMessageResponse
	(*GetHistoryRequest)(nil),     // 6: messenger.v1.GetHistoryRequest
	(*GetHistoryResponse)(nil),    // 7: messenger.v1.GetHistoryResponse
	(*ChatMessage)(nil),           // 8: messenger.v1.ChatMessage
	(*durationpb.Duration)(nil),   // 9: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_api_proto_messenger_v1_messenger_proto_depIdxs = []int32{
	9,  // 0: messenger.v1.CreateChatRequest.chat_ttl:type_name -> google.protobuf.Duration
	9,  // 1: messenger.v1.CreateChatRequest.message_ttl:type_name -> google.protobuf.Duration
	8,  // 2: messenger.v1.GetHistoryResponse.messages:type_name -> messenger.v1.ChatMessage
	10, // 3: messenger.v1.ChatMessage.sent_at:type_name -> google.protobuf.Timestamp
	0,  // 4: messenger.v1.Messenger.CreateSession:input_type -> messenger.v1.CreateSessionRequest
	2,  // 5: messenger.v1.Messenger.CreateChat:input_type -> messenger.v1.CreateChatRequest
	4,  // 6: messenger.v1.Messenger.SendMessage:input_type -> messenger.v1.SendMessageRequest
	6,  // 7: messenger.v1.Messenger.GetHistory:input_type -> messenger.v1.GetHistoryRequest
	1,  // 8: messenger.v1.Messenger.CreateSession:output_type -> messenger.v1.CreateSessionResponse
	3,  // 9: messenger.v1.Messenger.CreateChat:output_type -> messenger.v1.CreateChatResponse
	5,  // 10: messenger.v1.Messenger.SendMessage:output_type -> messenger.v1.SendMessageResponse
	7,  // 11: messenger.v1.Messenger.GetHistory:output_type -> messenger.v1.GetHistoryResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_messenger_v1_messenger_proto_init() }
func file_api_proto_messenger_v1_messenger_proto_init() {
	if File_api_proto_messenger_v1_messenger_proto != nil {
		return
	}
	file_api_proto_messenger_v1_messenger_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_messenger_v1_messenger_proto_rawDesc), len(file_api_proto_messenger_v1_messenger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_messenger_v1_messenger_proto_goTypes,
		DependencyIndexes: file_api_proto_messenger_v1_messenger_proto_depIdxs,
		MessageInfos:      file_api_proto_messenger_v1_messenger_proto_msgTypes,
	}.Build()
	File_api_proto_messenger_v1_messenger_proto = out.File
	file_api_proto_messenger_v1_messenger_proto_goTypes = nil
	file_api_proto_messenger_v1_messenger_proto_depIdxs = nil
}
